spring.application.name=Manager
server.port=8080

# Dùng CustomUserDetailsService — không tạo user in-memory
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration

jwt.secret=K8mP2vN9qR4tY7wX1zA5cE8hJ3nB6dF0uL9sG2iQ5oV8yM4pT7rW1xC6eH0kA3bN
jwt.access-token-seconds=900
jwt.refresh-token-seconds=259200
jwt.cookie-secure=false

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/manager_vnd?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
